In [39]:
import torch
import numpy as np

# Tensors
The basic working units of **Pytorch** are tensors

In [40]:
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand notation for `4.0` which indicate that you want to create a floating point number.

In [41]:
t1.dtype

torch.float32

Now to create more complex tensors
- 1D Arrays (Vectors)
- 2D Arrays (Matrix)
- 3D Arrays

In [42]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [43]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [44]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions and different lengths along each dimension. However, the size of each dimension needs to be consistent i.e. the shape cannot be *improper*

In [45]:
print(t1.shape,
      t2.shape,
      t3.shape,
      t4.shape)

torch.Size([]) torch.Size([4]) torch.Size([3, 2]) torch.Size([2, 2, 3])


# Tensor Operations and Gradients

In [46]:
# Create tensors.
x = torch.tensor(3., requires_grad=False)
# or x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: `x`, `w`, and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`.

In [51]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have `requires_grad` set to `True` i.e. `w` and `b`. This feature of PyTorch is called autograd (automatic gradients). The `backward()` function stores the gradient in the `.grad` property of the tensors

In [52]:
# Compute derivatives
y.backward()

In [53]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(2.)


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`.

The "grad" in `w.grad` is short for *gradient*, which is another term for *derivative*. The term gradient is primarily used while dealing with vectors and matrices.

# Interoperability with Numpy
Numpy is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

- Pandas for file I/O and data analysis
- Matplotlib for plotting and visualization
- OpenCV for image and video processing

In [50]:
# Initialising an array
p = np.array([[1, 2], [3, 4.]])
print(p)
# Converting from array in numpy to tensor in pytorch
q = torch.from_numpy(p)
print(q)
# Converting from tensor in pytorch to array in numpy
r = q.numpy()
print(r)

[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
[[1. 2.]
 [3. 4.]]


***